spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/mydatabase}
    username: ${SPRING_DATASOURCE_USERNAME:myuser}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
    hikari:
      maximum-pool-size: 10
  jpa:
    show-sql: false

logging:
  level:
    com.imin.iminapi: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

server:
  port: ${SERVER_PORT:8085}
