package com.imin.iminapi.security;

public enum ErrorCode {
    FIELD_INVALID,
    INVALID_REQUEST,
    AUTH_MISSING,
    AUTH_INVALID_CREDENTIALS,
    AUTH_TOKEN_EXPIRED,
    FORBIDDEN,
    ORG_PLAN_LIMIT,
    NOT_FOUND,
    STALE_WRITE,
    INVALID_STATE,
    DUPLICATE,
    PUBLISH_VALIDATION_FAILED,
    RATE_LIMITED,
    INTERNAL,
    UPSTREAM_UNAVAILABLE
}
