package com.imin.iminapi.security;

public enum ErrorCode {
    FIELD_INVALID,
    INVALID_REQUEST,
    AUTH_MISSING,
    AUTH_INVALID_CREDENTIALS,
    AUTH_TOKEN_EXPIRED,
    EMAIL_NOT_VERIFIED,
    INVALID_CODE,
    INVALID_TOKEN,
    FORBIDDEN,
    ORG_PLAN_LIMIT,
    NOT_FOUND,
    STALE_WRITE,
    INVALID_STATE,
    DUPLICATE,
    PRICE_CHANGED,
    PUBLISH_VALIDATION_FAILED,
    STRIPE_NOT_READY,
    COUNTRY_NOT_ALLOWED,
    RATE_LIMITED,
    INTERNAL,
    UPSTREAM_UNAVAILABLE
}
